### ISSUE TITLE
NULL Handling

### ISSUE THREAD

**Issue by maxashwin** [balaji-kommuru/PCAP-PARSER#8]
Problem identification: NULL Handling
Severity: critical
Risk: high 
Problem description: parser.c:109 & 25 – The fread returns total number of elements successfully read as a size_t object. If this number differs from the nmemb parameter, then either an error had occurred or the End Of File was reached. A NULL was deliberated inserted in the pcap file which was not handled by the readType(FILE* file) function. This bug leads to a Segmentation Fault, wherein even a normal user is able to crash the program.
Remediation: Handle NULL return type when readBytes function is called.

**Comment by MartinSarkany** [comment]
accidentally resolved in previous commit
